apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: import-mysql
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            parent: "import-cron"
        spec:
          successfulJobsHistoryLimit: 2
          containers:
          - name: import-mysql
            image: fedora
            command: ['curl', 'http://buildinterfaceserver-art-build-dev.cloud.paas.psi.redhat.com/build']
          restartPolicy: OnFailure